### ISSUE TITLE
Package Update and Notification System Improvements

### ISSUE THREAD

**Issue by noisecode3** [SlackBuildsOrg/slackbuilds#7104]
Summary:
Critical packages are not being updated in a timely manner, leading to security and functionality issues. Specifically, the tor package is outdated and non-functional. Additionally, the nordvpn package needs an urgent update due to security risks.

Details:
    Issue with tor Package:
        The current version of the tor package is outdated and does not work correctly.
        There is a syntax error in the rc.tor script at [line 38](https://github.com/SlackBuildsOrg/slackbuilds/blob/master/network/tor/rc.tor#L38):
            The line should use a colon (:) instead of a period (.).

    Urgent nordvpn Package Update:
        The nordvpn package poses a security risk due to its outdated version.
        Regular manual updates are required, which is inconvenient and not a long-term solution.

Proposed Solution:
    Implement a system to tag critical packages that need regular updates.
    Automatically notify maintainers when these critical packages have updates available.
    Ensure that high-priority packages like tor and nordvpn are kept up to date to avoid security risks and functionality issues.

Impact:
    Outdated and non-functional packages cause inconvenience and potential security vulnerabilities for users.
    Automating the update notification process will improve package maintenance efficiency and security.

Thank you for addressing these issues.

**Comment by willysr** [comment]
hi
it's already covered in our FAQ
https://slackbuilds.org/faq/#bugs
https://slackbuilds.org/faq/#version_update

feel free to send a notification to our mailing list as well

**Comment by noisecode3** [comment]
Hi,

Thank you for your response.

I am aware of the guidelines mentioned in the FAQ. However, I believe the current system is not effective for several reasons:

    Lack of Immediate Response:
        Reporting issues via the mailing list or to individual developers often leads to delayed responses. By this time, users may have already resolved the issues manually, which defeats the purpose of having an update system.

    User Engagement:
        It seems that not enough users are reporting issues or engaging with the mailing list, which further slows down the process of updating critical packages.

    Critical Package Updates:
        For packages with significant security implications, like tor and nordvpn, timely updates are crucial. Relying on manual reporting and updates does not seem adequate for maintaining security and functionality.

I suggest implementing a more automated system for tagging and notifying maintainers about critical updates. With more rules for how long that should take. This could ensure timely responses and reduce the manual effort required from users.

Thank you for considering this feedback.

Best regards,

Martin

**Comment by noisecode3** [comment]
We could implement a script that automatically checks for the latest version of critical packages. If a new version is found, the maintainer would be notified and given a 5-day window to respond with an update. If there is no response within this period, the package would be flagged as "unmaintained" in the info file and/or the site and could be reassigned to a new maintainer.

This approach would ensure that critical packages are updated promptly and reduce the manual effort currently required.
The user would it least in the end know a manual update is currently required instead of needing to constantly check this elsewhere..

Example:
```
import requests
import time
import json

# GitHub repository details
REPO_OWNER = "NordSecurity"
REPO_NAME = "nordvpn-linux"

# File to store the latest version
VERSION_FILE = "latest_version.txt"

def get_latest_release():
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases/latest"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json().get("tag_name")
    return None

def get_latest_tag():
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/tags"
    response = requests.get(url)
    if response.status_code == 200:
        tags = response.json()
        if tags:
            return tags[0].get("name")
    return None

def load_latest_version():
    try:
        with open(VERSION_FILE, "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        return None

def save_latest_version(version):
    with open(VERSION_FILE, "w") as f:
        f.write(version)

def check_for_updates():
    latest_release = get_latest_release()
    latest_tag = get_latest_tag()
    
    if latest_release and latest_tag:
        latest_version = max(latest_release, latest_tag)
    elif latest_release:
        latest_version = latest_release
    elif latest_tag:
        latest_version = latest_tag
    else:
        return

    stored_version = load_latest_version()

    if not stored_version or latest_version > stored_version:
        print(f"New version found: {latest_version}")
        save_latest_version(latest_version)
    else:
        print(f"No new version. Latest version is still {stored_version}")

if __name__ == "__main__":
    while True:
        check_for_updates()
        time.sleep(86400)  # Check every 24 hours (86400 seconds)

```

**Comment by willysr** [comment]
how do you define critical?
one package might be critical for me, but others, probably don't use it

5 days is too short. We are doing this work voluntarily in our spare time. We might be on holiday, so if you need to update the script, feel free to change the VERSION in .info and .SlackBuild and run the script.
If all scripts should be changed within 5 days, we would end up with lots of scripts in an orphaned state. Some maintainers have their own opinions on keeping a specific version of a script. Some can't be updated due to dependencies not being met by Slackware 15.0.

Remember that we only provide scripts to build sources into native Slackware packages and it's still users' job to keep their software updated using the existing scripts in the repository.

**Comment by rworkman** [comment]
What willysr said <-- the answer

**Comment by noisecode3** [comment]
> how do you define critical?
one package might be critical for me, but others, probably don't use it

This is objective, that would be most high risk client software like a web browse, DBMS, email client, skype and so on.
Also firewall, vpn, passworkmanager and backup software. That would be about 20-40 packages.

> Remember that we only provide scripts to build sources into native Slackware packages and it's still users' job to keep their software updated using the existing scripts in the repository.

Yes, and that's fine if you want that to stay the case for all packages like it is right now.

**Comment by willysr** [comment]
> There is a syntax error in the rc.tor script at [line 38](https://github.com/SlackBuildsOrg/slackbuilds/blob/master/network/tor/rc.tor#L38):
> The line should use a colon (:) instead of a period (.).

this is a side effect of coreutil package update in stable, but it shouldn't pose a problem, but @rworkman managed to work on that which can be seen on this branch:  https://git.slackbuilds.org/slackbuilds/log/?h=chown_and_backtick_fixes
it should be merged with this week's update

**Comment by aclemons** [comment]
I understand your motivation here @noisecode3, but as @willysr and @rworkman have pointed out, it is not really feasible to do what you are asking in the scope of how slackbuilds.org works. Even if we could agree on what "critical" is, we don't even require real e-mail address in .info files. We also only publish updates once a week. This means even if we automatically determined that a package is out of date, most likely we'd need a human to actually contact the maintainer. Then we'd need machinery to track responses of things that have not been followed up etc etc.

As @willysr said, we are doing this in our free time and currently, Willy and I are mostly handling the weekly updates, and by that I mean mostly Willy is doing the hard work and I try to help out a bit here and there.

Fortunately, there is a very simple way for you to keep your system updated and only for your critical packages that you care about and without waiting for a weekly update. (Assuming simply versions bumps do not break the script)

Fork this repo, add the [Mend renovate app](https://github.com/marketplace/renovate) to your repo and then setup a `.github/renovate.json` configuration with your "critical" packages. The app will open PRs for you. You can change the MD5SUMs and merge those into your master branch and rebuild your packages. 

Each week rebase from the SlackBuildsOrg/slackbuilds master branch after the public updates, drop any of your commits related to packages that have now been updated by the maintainer. You can even contact those maintainers who you feel like have not updated something in a timely manner.

Here is a configuration which will track nordvpn and tor. Simply add more regular expressions for other packages you care about:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:best-practices"
  ],
  "packageRules": [
    {
      "description": "Disable updates for docker, github actions, gitlab ci, and go mod files.",
      "matchManagers": ["dockerfile", "github-actions", "gitlabci", "gomod"],
      "enabled": false
    }
  ],
  "customManagers": [
    {
      "customType": "regex",
      "datasourceTemplate": "github-releases",
      "depNameTemplate": "NordSecurity/nordvpn-linux",
      "fileMatch": [
        "^network/nordvpn/nordvpn\\.SlackBuild$",
        "^network/nordvpn/nordvpn\\.info$"
      ],
      "matchStrings": [
        "VERSION=\\${VERSION:-(?<currentValue>.*?)}",
        "VERSION=\"(?<currentValue>.*?)\"",
        "pool/main/nordvpn_(?<currentValue>.*?)_"
      ]
    },
    {
      "customType": "regex",
      "datasourceTemplate": "repology",
      "depNameTemplate": "freebsd/tor",
      "fileMatch": [
        "^network/tor/tor\\.SlackBuild$",
        "^network/tor/tor\\.info$"
      ],
      "matchStrings": [
        "VERSION=\\${VERSION:-(?<currentValue>.*?)}",
        "VERSION=\"(?<currentValue>.*?)\"",
        "torproject.org/tor-(?<currentValue>.*?)\\.tar\\.gz"
      ],
      "versioningTemplate": "loose"
    }
  ]
}
```

I've tested it and you will get PRs for both:

![renovate](https://github.com/user-attachments/assets/27dd1fbb-8896-469d-82de-28bf0d657b44)

There are many [datasources](https://docs.renovatebot.com/modules/datasource/) you can use to pull the version information. Things on github are the simplest and the example above uses that for norvpn. Otherwise, you can also source versions from repology by choosing the distribution you trust to give timely updates and setting it as the source (see the tor example above tracking freebsd).

You can even set this up for any packages you maintain to get notifications of new releases.

I hope this helps.

**Comment by noisecode3** [comment]
@aclemons That looks like an amazing solution. I'm going to try it. I will only do that for the ones I use because there needs to be a real human at the end using the package for testing and verifying its functionality after the automated change. It also helps me maintain my own packages. Thanks.
