### ISSUE TITLE
graphics/birdfont install directly to filesystem

### ISSUE THREAD

**Issue by willysr** [SlackBuildsOrg/slackbuilds#8040]
birdfont doesn't properly place the files into $PKG but directly into the filesystem
it was discovered when i tried to patch webkit2gtk and build every other scripts that depends on it
since the resulting package is still created, sbopkglint didn't label this as incorrect output, but there were no content except for some documentations inside the resulting package.

cc @giandex

**Comment by giandex** [comment]
Willy, could you help me to find the issue?
I checked in -current (at the moment) and this issue does not happen.
I followed these steps:
1) removed the birdfont package installation
2) checked if some files included in the packages remained in the system (for example /usr/bin/birdfont or /usr/lib64/libbird*): none of these files were found
3) rebuilt the package without installing it
4) checked the content of the birdfont*tgz archive. You wrote "but there were no content except for some documentations inside the resulting package", but this is the result of directory tree where I unpacked the tgz archive:

`
.
├── install
│   ├── doinst.sh
│   └── slack-desc
└── usr
    ├── bin
    │   ├── birdfont
    │   ├── birdfont-autotrace
    │   ├── birdfont-export
    │   └── birdfont-import
    ├── doc
    │   └── birdfont-2.33.4
    │       ├── AUTHORS
    │       ├── GPLv3.txt
    │       ├── LGPLv3.txt
    │       ├── NEWS
    │       ├── README.md
    │       ├── TRANSLATORS
    │       └── birdfont.SlackBuild
    ├── lib64
    │   ├── libbirdfont.so.36.0
    │   └── libbirdgems.so.0.0
    ├── man
    │   └── man1
    │       ├── birdfont-autotrace.1.gz
    │       ├── birdfont-export.1.gz
    │       ├── birdfont-import.1.gz
    │       └── birdfont.1.gz
    └── share
        ├── applications
        │   └── birdfont.desktop
        ├── birdfont
        │   ├── Roboto-Regular.ttf
        │   ├── birdfont_window_icon.png
        │   ├── bright.theme
        │   ├── codepages.sqlite
        │   ├── dark.theme
        │   ├── high_contrast.theme
        │   ├── icons.birdfont
        │   ├── key_bindings.xml
        │   └── ucd.sqlite
        ├── icons
        │   └── hicolor
        │       ├── 128x128
        │       │   └── apps
        │       │       └── birdfont.png
        │       ├── 256x256
        │       │   └── apps
        │       │       └── birdfont.png
        │       └── 48x48
        │           └── apps
        │               └── birdfont.png
        ├── locale
        │   ├── cs
        │   │   └── LC_MESSAGES
        │   │       └── birdfont.mo
        │   ├── de
        │   │   └── LC_MESSAGES
        │   │       └── birdfont.mo
        │   ├── es
        │   │   └── LC_MESSAGES
        │   │       └── birdfont.mo
        │   ├── it
        │   │   └── LC_MESSAGES
        │   │       └── birdfont.mo
        │   ├── nl
        │   │   └── LC_MESSAGES
        │   │       └── birdfont.mo
        │   ├── pt_BR
        │   │   └── LC_MESSAGES
        │   │       └── birdfont.mo
        │   └── sv
        │       └── LC_MESSAGES
        │           └── birdfont.mo
        ├── metainfo
        │   └── birdfont.appdata.xml
        └── mime
            └── packages
                └── birdfont.xml

`

5. checked if these files are present in the system (without installing the package). None of these were found

This happens in current. I'm going to check if the issue happens in stable

**Comment by giandex** [comment]
Followed same steps in stable, the build proceeded regularly: all files were moved in $PKG and included in the package, not in the system.

Please note that I've installed in my systems webkit2gtk4.1 version 2.44.2, not the latest (2.44.4). Could it be relevant? I have to upgrade webkit2gtk to 2.44.4 but not today, I'm busy, maybe tomorrow

**Comment by willysr** [comment]
this is the original result of your birdfont 
https://github.com/SlackBuildsOrg/slackbuilds/pull/8038#issuecomment-2353033342

**Comment by giandex** [comment]
mmm... 
I didn't see in the stream of your slackbuild, let me know: does your slackbuild script apply the patch install-path.patch?
Disabling this patch, I reproduced the same issue: all files will be installed in the filesystem

This occurs because ./configure is runned with these options:
` ./configure --prefix=/usr --dest=/ `

The patch changes the option --prefix with /tmp/SBo/package-birdfont/ . I had to add this patch because sbopkglint does not pass the slackbuild with this line:
` ./configure --prefix=/tmp/SBo/package-birdfont/ --dest=/ `
but disabling the patch, the script install.py will install all files in the /usr directory of filesystem!

**Comment by giandex** [comment]
Sorry: -prefix=/tmp/SBo/package-birdfont/usr

**Comment by willysr** [comment]
If you look at the SlackBuild (https://slackbuilds.org/slackbuilds/15.0/graphics/birdfont/birdfont.SlackBuild), you will see that it will apply the patch you place there

**Comment by giandex** [comment]
I tried also after upgrade of webkit2gtk but nothing has changed. I'm not able to reproduce the issue in no other way than disabling the patch.

Try this:
1) disable the patch
2) edit the slackbuild script with
` ./configure --prefix=$CWD/usr --dest=/  `

Let me know what happens. If it works, in any case sbopkglint will return some errors, but I have to find another solution

**Comment by willysr** [comment]
$CWD? shouldn't it be $PKG?

**Comment by giandex** [comment]
Sorry! $PKG

**Comment by giandex** [comment]
This is not a solution because the build set the path with /tmp/SBo  in the library /usr/lib64/libbirdfont.so.* :-\

I must go to work now, I will see in the afternoon

**Comment by willysr** [comment]
@giandex see here: https://github.com/SlackBuildsOrg/slackbuilds/pull/8038#issuecomment-2354571178
this should work properly now

if you want to see the diff: it's here: https://github.com/SlackBuildsOrg/slackbuilds/commit/36508414804efa52cbf85dcc173562c8cc75218e

**Comment by giandex** [comment]
Good! it works.
I have to submit a little update because a fix is required to change permissions:
Running test: 05-basic-sanity...
--- usr/share/mime should not contain files with executable permission:
-rwxr-xr-x 1 root root 362 set 17 17:02 usr/share/mime/application/birdfont.xml
FAILED
....
Running test: 20-arch...
--- ELF binaries/libraries should be executable:
-rw-r--r-- 1 root root 30824 set 17 17:02 usr/lib64/libbirdgems.so.0.0
-rw-r--r-- 1 root root 4072816 set 17 17:02 usr/lib64/libbirdfont.so.36.0
FAILED

The second failure were fixed with the removed patch, so I have to edit this.

The first failure (executable permission) is an issue that I can't solve at the moment: 
the file /usr/share/mime/application/birdfont.xml is not included in the package but it is installed by doinst.sh. I tried to change the permission via doinst.sh as following:

`
if [ -x /usr/bin/update-mime-database ]; then
  /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
  chmod 644 /usr/share/mime/application/birdfont.xml
fi

`
It works, the executable permission of birdfont.xml has been removed, but sbopkglint returns still the failure. I have to find where is the origin of the issue and fix it properly

**Comment by willysr** [comment]
on my patch, it doesn't have any issues with birdfont.xml permission
if you want to change it, try change it in the SlackBuild like chmod 644 $PKG/usr/share/mime/applications/birdfont.xml

as for second failure, you can ignore it

**Comment by giandex** [comment]
I posted the question in mailing-list, is a condition of -current (my default system): all XML files in /usr/share/mime/application have executable permission due the different version of shared-mime-info

**Comment by willysr** [comment]
that's more reason not to test scripts for SBo under -current :)
